version: '3.9'

services:
  app:
    build: .
    container_name: its-time-to-go
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - its-time-to-go
  mariadb:
    image: mariadb:10.7
    container_name: mariadb-its-time-to-go
    ports:
      - 3306:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=its_time_to_go
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - its-time-to-go
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  dbvolume:

networks:
  its-time-to-go:
